/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigurationPanel.java
 *
 * Created on Jan 6, 2012, 5:34:34 AM
 */
package fuse4j.hadoopfs.gui;

import fuse4j.hadoopfs.config.Configuration;
import java.io.IOException;
import javax.swing.JDialog;

/**
 * @author petru
 */
public class ConfigurationPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	
	private Configuration configuration;
    
	/** Creates new form ConfigurationPanel */
    public ConfigurationPanel() {
        initComponents();
    }

    public ConfigurationPanel(Configuration configuration) {
    	this.configuration = configuration;
    	initComponents();
    	this.hdfsUrlField.setText(configuration.getHdfsUrl());
    	this.mountPointField.setText(configuration.getMountPoint());
    	this.usernameField.setText(configuration.getUsername());
    }

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 4), new java.awt.Dimension(0, 4), new java.awt.Dimension(32767, 4));
        jLabel1 = new javax.swing.JLabel();
        mountPointField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hdfsUrlField = new javax.swing.JTextField();
        saveConfigurationButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameField.setSize(200, 200);

        setBorder(javax.swing.BorderFactory.createTitledBorder("Fuse Hdfs configuration"));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("at location:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel1, gridBagConstraints);

        mountPointField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountPointFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(mountPointField, gridBagConstraints);

        jLabel2.setText("Mount HDFS url");
        add(jLabel2, new java.awt.GridBagConstraints());

        hdfsUrlField.setToolTipText("HDFS url");
        hdfsUrlField.setMinimumSize(new java.awt.Dimension(100, 100));
        hdfsUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdfsUrlFieldActionPerformed(evt);
            }
        });
        add(hdfsUrlField, new java.awt.GridBagConstraints());

        saveConfigurationButton.setText("Save configuration");
        saveConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveConfigurationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        add(saveConfigurationButton, gridBagConstraints);

        jLabel3.setText("as user:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(usernameField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void mountPointFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountPointFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_mountPointFieldActionPerformed

private void hdfsUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdfsUrlFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_hdfsUrlFieldActionPerformed

private void saveConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConfigurationButtonActionPerformed
        try {
            this.configuration.setHdfsUrl(hdfsUrlField.getText());
            this.configuration.setMountPoint(mountPointField.getText());
            this.configuration.setUsername(usernameField.getText());
            this.configuration.save(Configuration.getDefaultUserConfigurationPath());
            JDialog dialog = (JDialog) this.getRootPane().getParent();
            dialog.dispose();
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
}//GEN-LAST:event_saveConfigurationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextField hdfsUrlField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mountPointField;
    private javax.swing.JButton saveConfigurationButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
